# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "~> 0.14.11"
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.7.1"
    }
    helm = {
      source = "hashicorp/helm"
      version = "~> 2.4.1"
    }
  }
}
