# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 0.13.5"
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = ">= 2.6.0"
    }
    helm = {
      source = "hashicorp/helm"
      version = ">= 2.4.1"
    }
  }
}
