# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "consul" {
    address = "consul.service.dc01.local:8500"
    path    = "tfstate/operator/kubernetes-event-exporter/terraform.tfstate"
    scheme  = "https"
  }
}
