# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "consul" {}
}
provider kubernetes {
  config_path = "~/.kube/config"
  config_context = "kubernetes-admin@central"
}
provider helm {
  kubernetes {
    config_path = "~/.kube/config"
    config_context = "kubernetes-admin@central"
  }
}
module "namespace" {
  source = "git::https://github.com/goldstrike77/terraform-module-kubernetes.git//namespace?ref=v0.1"
  deploy_spec = var.deploy_spec
  annotations = var.annotations
  labels = var.labels
}
module "helm" {
  depends_on = [module.namespace]
  source = "git::https://github.com/goldstrike77/terraform-module-kubernetes.git//helm?ref=v0.1"
  deploy_spec = var.deploy_spec
}
